version: '3'

services:
  redis_db:
    image: 'redis:alpine3.18'
    container_name: 'redis_db'
    ports:
      - '6379:6379'
  abf_service:
    ports: 
      - '5050:5050'
    build:
      context: ./..
      dockerfile: ./Dockerfile
    depends_on:
      - redis_db
    links: 
      - redis_db