POST http://localhost:5050/try HTTP/1.1

{  
        "login":  "login",
        "password":  "password",
        "ip":  "33.33.33.2344"
}

###
POST http://localhost:5050/whitelist HTTP/1.1

{  
        "network":  "33.33.33.33/24"
}

###
DELETE  http://localhost:5050/whitelist HTTP/1.1

{  
        "network":  "33.33.33.33/24"
}
###
POST http://localhost:5050/blacklist HTTP/1.1

{  
        "network":  "33.33.33.33/24"
}

###
DELETE  http://localhost:5050/blacklist HTTP/1.1

{  
        "network":  "33.33.33.33/24"
}

###
POST http://localhost:5050/reset HTTP/1.1

{  
        "login":  "login",
        "password":  "password",
        "ip":  "33.33.33.33"
}