[logger]
level = "DEBUG"
out = ["logs/log.log"]
out_err = ["logs/log_err.log"]

[redis]
addr = "redis_db:6379"
password = ""
db = 0

[limiter]
n = 10
m = 100
k = 100

[server]
host = "0.0.0.0"
port = ":5050"